### ISSUE TITLE
Extension to bioenergetics

### ISSUE THREAD

**Issue by AQ18** [EPFL-LCSB/skimpy#6]
I am interested in using SKiMpy to study the interaction of the bioenergetic network (proton pumps, ATPases and associated transporter processes that are powered by the membrane potential/ion motive forces) with the metabolic network. It seems that ion translocation can be represented in this framework by the small molecule modifiers, which I presume automatically accounts for the chemical potentials:
```
ATPS4rpp:
  enzyme: null
  mechanism:
    class: BiUniReversibleHill
    product: atp_c
    substrate1: pi_c
    substrate2: adp_c
  modifiers:
    DSM_h_c:
      class: DisplacementSmallMoleculeModifier
      mechanism_stoichiometry:
        small_molecule: 3.0
      small_molecule: h_c
    DSM_h_e:
      class: DisplacementSmallMoleculeModifier
      mechanism_stoichiometry:
        small_molecule: -4.0
      small_molecule: h_e
  name: ATPS4rpp
```

I am wondering if/how the membrane potential is represented as a thermodynamic driver as well as a dynamic variable to be calculated by the model, or if it is not already implemented, whether there is a clear path to doing so.
